-- 코드를 입력하세요
SELECT T.SALES_DATE, T.PRODUCT_ID, T.USER_ID, T.SALES_AMOUNT
FROM (
    SELECT ONLINE_SALE_ID, USER_ID,	PRODUCT_ID,	SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE
    UNION ALL
    SELECT OFFLINE_SALE_ID, NULL AS USER_ID, PRODUCT_ID,	SALES_AMOUNT, SALES_DATE FROM OFFLINE_SALE
     ) T
WHERE DATE_FORMAT(T.SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY T.SALES_DATE, T.PRODUCT_ID, T.USER_ID;