-- 코드를 입력하세요
SELECT T.USER_ID, T.PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) AS CNT
    FROM ONLINE_SALE 
    GROUP BY USER_ID, PRODUCT_ID ) AS T
WHERE T.CNT >= 2
ORDER BY T.USER_ID, T.PRODUCT_ID DESC;
